version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12 # Use your desired version
              environment:
                  NODE_ENV: development # Only needed if puppeteer is in `devDependencies`
        steps:
            - checkout
            - run:
                  name: Run tests
                  command: npm run test
