version: 2.1

orbs:
    puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
    build:
        docker:
            - image: circleci/node:12 # Use your desired version
              environment:
                  NODE_ENV: development # Only needed if puppeteer is in `devDependencies`
        steps:
            - checkout
            - run:
                  name: Set up dependencies
                  command: npm install
            - run:
                  name: Run tests
                  command: npm run test
