version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
    build:
        docker:
            - image: circleci/node:12 # Use your desired version
              environment:
                  NODE_ENV: development # Only needed if puppeteer is in `devDependencies`
workflows:
    node-tests:
        jobs:
            - node/test
